/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_TestDib */

#ifndef _Included_jni_TestDib
#define _Included_jni_TestDib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_TestDib
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_TestDib_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
