/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
#include "jni_TestDib.h"
#include <stdio.h>
JNIEXPORT void JNICALL Java_jni_TestDib_hello(JNIEnv *env, jobject obj){
   printf("Hello, world!\n");
}

 for(int i = 0; i < length; i++){
        		for(int j = i; j < length; j++){
               if(*(arrp + i)< *(arrp + j)){
                  int temp = *(arrp + i);
                  *(arrp+i) = *(arrp + j);
                  *(arrp+j) = temp;
               }
            }
        	}