/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Test */

#ifndef _Included_Test
#define _Included_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Test
 * Method:    helloFromC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CTest_helloFromC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif