/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jniValue_TestDic */

#ifndef _Included_jniValue_TestDic
#define _Included_jniValue_TestDic
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jniValue_TestDic
 * Method:    helloV
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jniValue_TestDic_helloV
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
