/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
#include "jniValue_TestDic.h"
#include <stdio.h>
JNIEXPORT void JNICALL Java_jniValue_TestDic_helloV(JNIEnv *env, jobject obj){
   printf("Hello, world c!\n");
}