/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CSO_Test */

#ifndef _Included_CSO_Test
#define _Included_CSO_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CSO_Test
 * Method:    add
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_CSO_Test_add
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
