/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnisort_LYGSortESU9D */

#ifndef _Included_jnisort_LYGSortESU9D
#define _Included_jnisort_LYGSortESU9D
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jnisort_LYGSortESU9D
 * Method:    jnisort
 * Signature: ([I[Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_jnisort_LYGSortESU9D_jnisort
  (JNIEnv *, jobject, jintArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
