/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
#include "jnisort_LYGSortESU9D.h"
//#include "jni_sortESU9D.h"
#include "jni_sortESU9D.c"
#include <stdio.h>
//extern void say();
//extern void quicksort(int* arrp, int lp, int rp, int deep);
//extern void partition(int* a, int lp, int rp, int* p);
JNIEXPORT jintArray JNICALL Java_jnisort_LYGSortESU9D_jnisort
  (JNIEnv *env, jobject obj, jintArray ar, jobjectArray ars){
      int length= (*env)->GetArrayLength(env, ar);
      int *arrp= (*env)->GetIntArrayElements(env, ar, 0);
      //printf("len-1\n");
      int arp[length];
      jstring jstr[length];
      for(int i = 0; i < length; i++){
         arp[i] = i;
         jstr[i] = (*env)->GetObjectArrayElement(env, ars, i);
      }
      //printf("len-2\n");
      processDouble(arp, arrp, 0, length - 1, 0);
      for(int i = 0; i < length; i++){
         (*env)->SetObjectArrayElement(env, ars, i, jstr[arp[i]]);
      }
      (*env)->SetIntArrayRegion(env, ar, 0, length, arrp);
      //printf("len-3\n");
      return ar;
  }
  //        char **arsp;//char speed less than int
  //        char * arsrp = (char *)(*env)->GetStringUTFChars(env, jstr[arp[i]], 0);
  //        char * arsrp = (char *)(*env)->GetStringUTFChars(env, jstr[i], 0);
  //        printf("len-2%d\n", arp[i]);
  //        printf("len-2%s\n", arsrp);
  //        printf("len--2%d\n", arp[i]);
  //        printf("len--2%s\n", arsrp);