/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jniFFT_LYGFFT */

#ifndef _Included_jniFFT_LYGFFT
#define _Included_jniFFT_LYGFFT
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jniFFT_LYGFFT
 * Method:    jnifft
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_jniFFT_LYGFFT_jnifft
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
