/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
#include "jniFFT_LYGFFT.h"
#include "jni_FFT.c"
#include <stdio.h>
JNIEXPORT jdoubleArray JNICALL Java_jniFFT_LYGFFT_jnifft
  (JNIEnv *env, jobject obj, jdoubleArray ar){
      int length= (*env)->GetArrayLength(env, ar);
      double *arrp= (*env)->GetDoubleArrayElements(env, ar, 0);
      double *arp;
      arp = fft1(arrp, length);
      (*env)->SetDoubleArrayRegion(env, ar, 0, length, arp);
      return ar;
  }